
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func dup2(oldfd int, newfd int) (err error) {
	_, _, e1 := Syscall(SYS_DUP2, uintptr(oldfd), uintptr(newfd), 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
