
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func schedSetattr(pid int, attr *SchedAttr, flags uint) (err error) {
	_, _, e1 := Syscall(SYS_SCHED_SETATTR, uintptr(pid), uintptr(unsafe.Pointer(attr)), uintptr(flags))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
