#!/bin/bash

set -e

[ $# -lt 1 ] && echo "Empty input" && exit 1
[ -z $1 ] || [ ! -d $1 ] && echo "Invalid input" && exit 1

WORK_DIR=$1
BASH_DIR=$( cd $( dirname ${BASH_SOURCE[0]:-$0} ) && pwd )

source ${BASH_DIR}/../../common.sh



# 2025-02-28 Rong
# sw64 files are generated based on https://github.com/containerd/continuity/tree/cf279e6ac893682272b4479d4c67fd3abf878b4e
# - copy_linux_sw64.go: generated by `GOOS=linux GOARCH=sw64 ./generate.sh copy`
# - xattr_linux_sw64.go: generated by `GOOS=linux GOARCH=sw64 ./generate.sh xattr`
# - sysnum_linux_sw64.go: written by hand
for i in copy sysnum xattr; do
	if [ -f ${WORK_DIR}/${i}_linux_386.go ]; then
		info "Creating: ${i}_linux_sw64.go"
		cp -f ${BASH_DIR}/${i}_linux_sw64.go ${WORK_DIR}/${i}_linux_sw64.go
	fi
done
success "Done."
