
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func fsconfig(fd int, cmd uint, key *byte, value *byte, aux int) (err error) {
	_, _, e1 := Syscall6(SYS_FSCONFIG, uintptr(fd), uintptr(cmd), uintptr(unsafe.Pointer(key)), uintptr(unsafe.Pointer(value)), uintptr(aux), 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
