
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func schedGetattr(pid int, attr *SchedAttr, size uint, flags uint) (err error) {
	_, _, e1 := Syscall6(SYS_SCHED_GETATTR, uintptr(pid), uintptr(unsafe.Pointer(attr)), uintptr(size), uintptr(flags), 0, 0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
