#!/bin/bash

set -e

[ $# -lt 1 ] && echo "Empty input" && exit 1
[ -z $1 ] || [ ! -d $1 ] && echo "Invalid input" && exit 1

WORK_DIR=$1
BASH_DIR=$( cd $( dirname ${BASH_SOURCE[0]:-$0} ) && pwd )

source ${BASH_DIR}/../../common.sh



info "Creating: zsysconf_values_linux_sw64.go"
# 2023-12-19 Rong: Generated by `$(go env GOROOT)/pkg/tool/linux_sw64/cgo -godefs sysconf_values_linux.go`
cp -f ${BASH_DIR}/zsysconf_values_linux_sw64.go ${WORK_DIR}/zsysconf_values_linux_sw64.go
success "Done."
